### PR TITLE
Remove the checkpoint reader from the Hindsight config struct

### PR DESCRIPTION
**Pull request by trink**
- output the fully merged configuration to disk for the admin UI

### CODE REVIEW

**Comment by bbinet** [comment]
What admin UI are you referring to?
Are you working on an opensource admin UI for Hindsight?

**Comment by trink** [comment]
Yes, the new repo will be available in about a week.  It allows monitoring of the hindsight.tsv file (plus stopped/terminated plugins) a source/cfg /log viewer.  The sandbox tester interface and plugin management (deploy/start/stop/restart) capabilities.  The grammar tester integration and graphical dashboard displays will follow in the coming weeks.

**Comment by bbinet** [comment]
That is great news!
I look forward to try it out when available.

**Comment by trink** [comment]
@bbinet well 'next week' didn't happen I got pulled off on other things.  However a lot of work was completed you can check out a pre-release here: https://hsadmin.trink.com/

**Comment by bbinet** [comment]
Thanks, it looks great.

**Pull request merged**
