### PR TITLE
Build mozilla/hindsight container and publish to DockerHub

### PR DESCRIPTION
**Pull request by jvehent**
This patch adds a Dockerfile that build hindsight on centos 7. The goal is to publish the resulting container on Mozilla's DockerHub repository so people can fetch it with `docker pull mozilla/hindsight`.

The configuration logic follows [Dockerflow](https://github.com/mozilla-services/Dockerflow/): a container is built on every branch, but only tagged branches trigger a push to DockerHub. I will take care of creating credentials and configure them in travisci shortly.

To function properly, the container needs a configuration file, so I added `hindsight.cfg` to the base directory. Let me know if this should be done differently.

Test locally with:
```bash
$ docker build -t mozilla/hindsight .
$ docker run mozilla/hindsight                 # starts hindsight with the default conf
$ docker run -it mozilla/hindsight /bin/bash   # starts a shell inside the container
```

### CODE REVIEW

**Comment by jvehent** [comment]
DockerHub configuration has been added to TravisCI, so once this is merged, tagging a release will trigger a push of the new container to mozilla/hindsight.

**Comment by sathieu** [comment]
Hello @jvehent.
Publishing a docker image requires to be carefull, as you'll need to support it for years.

Looking quickly, your proposal has several drawbacks:
- too many layers,
- the build tools are kept (making the image unnecessarily big, and increasing the attack surface)
- the path are not canonical (those should follow the official docs IMO)
- lua_sandbox_extensions is not included
- no volumes
- instead, it should reuse the already done, take the .rpms and install them in a *new* container

Regards

**Comment by sathieu** [comment]
> - the path are not canonical (those should follow the official docs IMO)

THe canonical path are at https://github.com/mozilla-services/hindsight/blob/master/docs/configuration.md

> - lua_sandbox_extensions is not included

The pakcages from https://github.com/mozilla-services/lua_sandbox_extensions/ should be installed (see the logstash image as example, "bateries included!")

> - no volumes

At least a volume for the config. See also <https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/>.

**Comment by jvehent** [comment]
@sathieu : What do you think of the following changes? It's still building from source, but all the dev tools are cleaned up at the end. The resulting image is around 350MB (base centos:7 is ~200MB). I don't think Docker's layering model allows for much more reduction in size...

I'm running it locally with test data taken from the `benchmarks` folder as follows: `$ docker run -it -v $(pwd)/input:/app/input -v $(pwd)/run:/app/run -v $(pwd)/output:/app/output mozilla/hindsight`

**Comment by jvehent** [comment]
Any further comment on this PR? I'd like to merge it and publish a container to mozilla/hindsight. Then we can improve on it.

**Pull request merged**
