### PR TITLE
Build docker image using Circle-CI

### PR DESCRIPTION
**Pull request by jasonthomas**
As part of project-manatee we would like to deploy hindsight into our environments via a docker container. As with most of our projects in cloud-services we use Circle-CI to build the docker image and push it into DockerHub. This PR add the Circle-CI configuration and also makes a few minor changes to the Dockerfile.

r?

### CODE REVIEW

**Comment by trink** [comment]
Please rebase this PR off the dev branch (and then switch the base for the merge) thanks.

**Comment by jasonthomas** [comment]
I've made the requested changes.

**Comment by jasonthomas** [comment]
Do you think it would be a good idea to build a docker image for the dev branch as well? Might be useful for testing.

**Comment by trink** [comment]
It could be useful but the current workflow has the sprint branch being merged into dev at the end of the sprint (basically the same time it lands in master).  However, we could start working some of those feature branches directly off of dev instead of the sprint branch and get some pre-release deployment/testing going so +1.

**Pull request merged**
