### PR TITLE
Stop slow analysis plugins

### PR DESCRIPTION
**Pull request by methodmissing**
@kvs pending tests, a zombie stab @ https://github.com/mozilla-services/hindsight/issues/78

### CODE REVIEW

**Comment by trink** [comment]
Thanks for the contribution however the intent of this bug is to terminate the plugin causing the back pressure and not stop Hindsight.

**Comment by methodmissing** [comment]
My bad, tail end of a long flight plan. I'll adjust behaviour to just term the analysis plugin

**Comment by trink** [comment]
There are a lot of edge cases (such as ways to create a cascading termination and wipe out everything or terminate the wrong plugin and not actually release the backpressure). We should spec out the requirements as we may require additional controls to make it useful/manageable (e.g. we may want to provide a do not terminate cfg option for individual plugins or exempt non user deployed plugins).

**Comment by methodmissing** [comment]
Agree, I will talk to @kvs this week about our cases thus far and open a dialog instead of a PR. We're also interested in contributing a thin Dockerfile as a base image for individual deployments and also learning operating it in a kubernetes environment with 2 distinct deployments at the moment. Thanks for the quick input!

**Pull request closed without merging**
